"use client";
import React from "react";
import { Edit2, Trash2, ExternalLink, CheckCircle, Package, Scale } from "lucide-react";

export interface MobileOrder { id:number; name:string; imageUrl:string|null; itemUrl:string|null; forWhom:string|null; trackNumber:string|null; status:string; quantity:number; priceCny:number; shippingBelarusByn:number|null; weight:number|null; plannedDate:string|null; receivedDate:string|null; itemTotalCny:number; itemCostByn:number; totalWithShippingByn:number; unitCostByn:number; shippingUsd:number; }
type Props = { orders:MobileOrder[]; defaultRate:number; cargoShippingUsdPerKg:number; selectedOrderIds:number[]; toggleOrderSelection:(id:number)=>void; updateOrderStatus:(id:number,status:string)=>void; updateInlineOrderField:(id:number,field:string,value:string)=>void; setOrders:React.Dispatch<React.SetStateAction<any[]>>; getEmbeddedImage:(o:any)=>string|null; setPreviewImage:(v:{src:string;name:string}|null)=>void; handleEditClick:(o:any)=>void; handleDeleteClick:(id:number,name:string)=>void; statusOptions:string[]; };

const tone=(s:string)=>s==="Прибыло в РБ"?"border-emerald-400/50 bg-emerald-500/15 text-emerald-300":s==="Едет в РБ"?"border-violet-400/50 bg-violet-500/15 text-violet-300":s==="На складе в Китае"?"border-amber-400/50 bg-amber-500/15 text-amber-300":s==="Выдано / Получено"?"border-slate-400/40 bg-slate-500/15 text-slate-300":"border-sky-400/50 bg-sky-500/15 text-sky-300";
const Field=({label,children}:{label:string;children:React.ReactNode})=><div className="rounded-xl bg-[#0a1a2b] border border-[#203b55] px-3 py-2.5 min-w-0"><div className="text-[9px] font-black uppercase tracking-wider text-slate-500 mb-1">{label}</div><div className="min-w-0 text-sm text-slate-100 font-semibold">{children}</div></div>;

export default function MobileOrderCards(p:Props){
 const {orders,defaultRate,cargoShippingUsdPerKg,selectedOrderIds,toggleOrderSelection,updateOrderStatus,updateInlineOrderField,setOrders,getEmbeddedImage,setPreviewImage,handleEditClick,handleDeleteClick,statusOptions}=p;
 return <div className="mobile-orders-list space-y-3">{orders.map(o=>{
  const image=o.imageUrl||getEmbeddedImage(o);
  return <article key={o.id} className="mobile-order-card rounded-2xl border border-[#294965] bg-[#0c2035] shadow-lg shadow-black/20 overflow-hidden">
   <div className="p-3.5">
    <div className="flex items-start gap-3">
     <input type="checkbox" checked={selectedOrderIds.includes(o.id)} onChange={()=>toggleOrderSelection(o.id)} className="mt-1.5 w-4 h-4 accent-blue-500 shrink-0" />
     <button type="button" onClick={()=>image&&setPreviewImage({src:image,name:o.name})} className="w-20 h-20 shrink-0 rounded-2xl overflow-hidden bg-[#071422] border border-[#294965] flex items-center justify-center">
      {image?<img src={image} alt={o.name} className="w-full h-full object-contain p-1" onError={e=>{(e.target as HTMLImageElement).style.display="none"}}/>:<Package className="w-7 h-7 text-slate-600"/>}
     </button>
     <div className="min-w-0 flex-1"><div className="text-[15px] leading-5 font-black text-white break-words">{o.name}</div><div className="mt-1 text-xs text-slate-400">Для: <span className="text-slate-200 font-semibold">{o.forWhom||"Родители"}</span></div>{o.itemUrl&&<a href={o.itemUrl} target="_blank" rel="noopener noreferrer" className="mt-1.5 inline-flex items-center gap-1 text-[10px] text-blue-400 font-bold">Открыть товар <ExternalLink className="w-3 h-3"/></a>}</div>
    </div>
    <select value={o.status} onChange={e=>updateOrderStatus(o.id,e.target.value)} className={"mt-3 w-full rounded-xl border px-3 py-2.5 text-xs font-black outline-none "+tone(o.status)}>{statusOptions.map(s=><option key={s} value={s} className="bg-slate-900 text-white">{s}</option>)}</select>
    <div className="mt-3 grid grid-cols-2 gap-2">
      <Field label="Количество"><input type="number" min="1" step="1" value={o.quantity} onChange={e=>setOrders(prev=>prev.map((x:any)=>x.id===o.id?{...x,quantity:Number(e.currentTarget.value)||0}:x))} onBlur={e=>updateInlineOrderField(o.id,"quantity",e.currentTarget.value)} className="w-full bg-transparent outline-none text-white font-black"/></Field>
      <Field label="Цена CNY / ед."><div className="flex items-center gap-1"><span className="text-amber-400">¥</span><input type="number" min="0" step="0.01" value={o.priceCny} onChange={e=>setOrders(prev=>prev.map((x:any)=>x.id===o.id?{...x,priceCny:Number(e.currentTarget.value)||0}:x))} onBlur={e=>updateInlineOrderField(o.id,"priceCny",e.currentTarget.value)} className="w-full min-w-0 bg-transparent outline-none text-white font-black"/></div></Field>
      <Field label="Сумма CNY"><span className="font-mono text-amber-300">¥ {o.itemTotalCny.toFixed(2)}</span></Field>
      <Field label="Курс"><span className="font-mono text-slate-300">{defaultRate.toFixed(4)}</span></Field>
      <Field label="Цена / ед. BYN"><span className="font-mono text-blue-300">{(o.priceCny*defaultRate).toFixed(2)} BYN</span></Field>
      <Field label="Сумма BYN"><span className="font-mono text-emerald-300">{o.itemCostByn.toFixed(2)} BYN</span></Field>
      <Field label="Карго из Китая"><div className="flex items-center justify-between gap-2"><span className="font-mono text-orange-300">${o.shippingUsd.toFixed(2)}</span><span className="text-[9px] text-slate-500 whitespace-nowrap">{(o.weight||0).toFixed(2)} кг × {cargoShippingUsdPerKg.toFixed(2)}</span></div></Field>
      <Field label="Доставка РБ"><div className="flex items-center gap-1"><input type="number" min="0" step="0.01" value={o.shippingBelarusByn??0} onChange={e=>setOrders(prev=>prev.map((x:any)=>x.id===o.id?{...x,shippingBelarusByn:Number(e.currentTarget.value)||0}:x))} onBlur={e=>updateInlineOrderField(o.id,"shippingBelarusByn",e.currentTarget.value)} className="w-full min-w-0 bg-transparent outline-none text-white font-black"/><span className="text-[10px] text-slate-500">BYN</span></div></Field>
    </div>
    <div className="mt-2 grid grid-cols-2 gap-2"><div className="rounded-xl border border-violet-400/30 bg-violet-500/10 px-3 py-3"><div className="text-[9px] font-black uppercase tracking-wider text-violet-300/70">Итого с доставкой</div><div className="mt-1 text-lg font-black font-mono text-violet-200">{o.totalWithShippingByn.toFixed(2)} <span className="text-xs">BYN</span></div></div><div className="rounded-xl border border-teal-400/30 bg-teal-500/10 px-3 py-3"><div className="text-[9px] font-black uppercase tracking-wider text-teal-300/70">Себестоимость 1 ед.</div><div className="mt-1 text-lg font-black font-mono text-teal-200">{o.unitCostByn.toFixed(2)} <span className="text-xs">BYN</span></div></div></div>
    <div className="mt-2 grid grid-cols-2 gap-2"><Field label="Вес"><div className="flex items-center gap-1"><Scale className="w-3.5 h-3.5 text-amber-400"/><input type="number" min="0" step="0.01" value={o.weight??0} onChange={e=>setOrders(prev=>prev.map((x:any)=>x.id===o.id?{...x,weight:Number(e.currentTarget.value)||0}:x))} onBlur={e=>updateInlineOrderField(o.id,"weight",e.currentTarget.value)} className="w-full min-w-0 bg-transparent outline-none text-amber-300 font-black"/><span className="text-[10px] text-slate-500">кг</span></div></Field><Field label="Трек-номер"><input value={o.trackNumber||""} placeholder="Не указан" onChange={e=>setOrders(prev=>prev.map((x:any)=>x.id===o.id?{...x,trackNumber:e.currentTarget.value}:x))} onBlur={e=>updateInlineOrderField(o.id,"trackNumber",e.currentTarget.value)} className="w-full min-w-0 bg-transparent outline-none text-white font-mono text-xs"/></Field></div>
    {(o.receivedDate||o.plannedDate)&&<div className="mt-2 rounded-xl bg-[#091827] border border-[#203b55] px-3 py-2 text-[10px]">{o.receivedDate?<span className="text-emerald-400 font-bold flex items-center gap-1"><CheckCircle className="w-3 h-3"/>Получен: {o.receivedDate}</span>:<span className="text-slate-400">План: <strong>{o.plannedDate}</strong></span>}</div>}
    <div className="mt-3 flex items-center gap-2 border-t border-[#203b55] pt-3"><button type="button" onClick={()=>handleEditClick(o)} className="flex-1 h-10 rounded-xl bg-blue-600/90 text-white text-xs font-black inline-flex items-center justify-center gap-1.5"><Edit2 className="w-4 h-4"/>Редактировать</button><button type="button" onClick={()=>handleDeleteClick(o.id,o.name)} className="w-10 h-10 rounded-xl bg-rose-500/10 border border-rose-500/30 text-rose-300 inline-flex items-center justify-center"><Trash2 className="w-4 h-4"/></button></div>
   </div>
  </article>
 })}</div>;
}